name: "[ClangTidy]"

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: fail
        if: steps.linter.outputs.checks-failed > 0
        run: echo "CHECKS FAILED. DETAILS IN LOGS"
        # for actual deployment
        # run: exit 1
